const express = require('express');
const router = express.Router();
const template =  require('../controller/templateController');
router.get('/', template.index);
router.get('/shop', template.shopGrid);
router.get('/shop-details', template.shopDetails);
router.get('/shoping-cart', template.shopCart);
router.get('/checkout', template.check);
router.get('/blog-details', template.details);
router.get('/blog', template.blog);
router.get('/contact', template.contacts);
module.exports = router;